name: Tjaard Heikens
favicon: null
layout_spectrum: 0.039013693341985345
typography_spectrum: 0.8439843885134906
title: Tjaard Heikens fotografie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03697254275903106
  lightness: 0.8255309695377946
  saturation: 0.6595461794640869
  rhythmicContrast: 0.11237234622240067
purpose: []
