typography_spectrum: 0.658
color:
  brandColors:
    - '#000000'
    - '#7783a6'
    - '#38425b'
    - '#c4c2c0'
    - '#3a6993'
  brandStrength: 0.125
  lightness: 0.8255309695377946
  saturation: 0.6595461794640869
  rhythmicContrast: 0.11237234622240067
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Tjaard Heikens
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Landscape
    id: 35f8b4df-06bd-47e5-bb65-1c75fcfc0afe
    type: content
favicon: null
title: Tjaard Heikens fotografie
description: Het bijzondere van het gewone
purpose: []
