name: Tjaard Heikens
favicon: null
layout_spectrum: 0
typography_spectrum: 0.658
title: Tjaard Heikens fotografie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7783a6'
    - '#38425b'
    - '#c4c2c0'
    - '#3a6993'
  brandStrength: 0.125
  lightness: 0.8255309695377946
  saturation: 0.6595461794640869
  rhythmicContrast: 0.11237234622240067
purpose: []
